property file changes
PSMRI/Common-API pull request #24
Opened 2023-07-03 13:19 UTC by helenKaryamsetty

2023-07-04 03:46 UTC, harimohanr requested changes
@helenKaryamsetty Please take a look at the comments for application.properties

2023-07-04 03:46 UTC, harimohanr commented on src/main/resources/application.properties
> +sms-username=PIRAMAL_SW_AHxoyCXejeJba13oKHcv
@helenKaryamsetty We should not keep any sensitive information like URL and credentials in public repository. Please revert this to the previous values. The values can be updated directly in war file during deployment.

2023-07-05 10:33 UTC, Vidyaaa24 submitted a review, later dismissed

2023-07-10 09:34 UTC, harimohanr approved these changes
@helenKaryamsetty Looks okay to me

2023-07-10 09:34 UTC, merged